User.find_or_initialize_by(email: 'admin@getarbor.io') do |user|
  user.full_name = 'Admin NeonRoots'
  user.password = 'password'
  user.password_confirmation = 'password'
  user.admin = true
  user.save
end

Project.find_or_initialize_by(is_template: true) do |project|
  project.name = 'Taxi Hailing App'
  stories_array = [
    { :role=>"user,",
      :action=>"to add a different credit card than the one I added during registration",
      :result=>"I can use a different method if I need to do so.",
      :estimated_points=>1 },
    { :role=>"user,",
      :action=>"to see my past history of rides I have taken",
      :result=>"I can track expenses and remember what I prefer.",
      :estimated_points=>3 },
    { :role=>"user,",
      :action=>"to select a location for home",
      :result=>"I can select it quickly when requesting a ride.",
      :estimated_points=>2 },
    { :role=>"user,",
      :action=>"to confirm my request for a vehicle",
      :result=>"Uber will send my car.",
      :estimated_points=>2},
    { :role=>"user,",
      :action=>"to cancel the reqest for a car",
      :result=>"I can change my mind if necessary.",
      :estimated_points=>1 },
    { :role=>"user,",
      :action=>"to add my mobile phone number",
      :result=>"my driver can contact me about my ride.",
      :estimated_points=>1 },
    { :role=>"user,",
      :action=>"to user my phone's camera to take a picture of my credit card",
      :result=>"I don't have to type in the information.",
      :estimated_points=>2 },
    { :role=>"user,",
      :action=>"to edit my account",
      :result=>"I can change my information.",
      :estimated_points=>5 },
    { :role=>"user,",
      :action=>"to edit my email",
      :result=>"I can update it if it has changed.",
      :estimated_points=>3 },
    { :role=>"user,",
      :action=>"to put in the location I wish to travel to ",
      :result=>"I can request a vehicle.",
      :estimated_points=>2 },
    { :role=>"user,",
      :action=>"to see where the car is in relation to me",
      :result=>"I have an idea of how far it is from me.",
      :estimated_points=>2 },
    { :role=>"user,",
      :action=>"to update my picture",
      :result=>"a picture shows on my profile.",
      :estimated_points=>2 },
    { :role=>"user,",
      :action=>"to edit my mobile number",
      :result=>"drivers can call the correct number to reach me.",
      :estimated_points=>1 },
    { :role=>"user,",
      :action=>"to add my credit card",
      :result=>"I can pay for my ride.",
      :estimated_points=>5 },
    { :role=>"user,",
      :action=>"to sign up for an account using my email",
      :result=>"I can request a ride.",
      :estimated_points=>5 },
    { :role=>"admin,", :action=>"to locate the user through geolocation",
      :result=>"I can show them if there are any available cars in their area.",
      :estimated_points=>5 },
    { :role=>"admin,",
      :action=>"to send a verification code to a newly registered user",
      :result=>"I can make sure they are not a spammer/scammer.",
      :estimated_points=>3 },
    { :role=>"user,",
      :action=>"to give feedback to my driver",
      :result=>"they are aware of my experience with the driver.",
      :estimated_points=>3 },
    { :role=>"user,",
      :action=>"to view the receipt when the ride is completed",
      :result=>"I know how much is being charged to my payment method.",
      :estimated_points=>1 },
    { :role=>"user,",
      :action=>"to send promotion codes to other users",
      :result=>"I can get a free ride.",
      :estimated_points=>2 },
    { :role=>"user,",
      :action=>" to see how many cars are available near me",
      :result=>"I can plan my trip.",
      :estimated_points=>5 },
    { :role=>"system,",
      :action=>"to calculate the price of a route based on mileage and pricing",
      :result=>"the passenger can see the estimates for their route.",
      :estimated_points=>3 },
    { :role=>"admin,",
      :action=>"to enter rates based on system demand",
      :result=>"I can properly estimate the price for a trip.",
      :estimated_points=>5 },
    { :role=>"user,",
      :action=>"to select text messages to receive information about my ride",
      :result=>"I can receive information quickly.",
      :estimated_points=>1 },
    { :role=>"system,",
      :action=>"to calculate the ideal route between the start and end of a trip",
      :result=>"I can calculate mileage.",
      :estimated_points=>5 },
    { :role=>"user,",
      :action=>"to input the verification code sent to me",
      :result=>"I can use the service.",
      :estimated_points=>1 },
    { :role=>"user,",
      :action=>"to click on a specific ride",
      :result=>"I can view the receipt from it.",
      :estimated_points=>3 },
    { :role=>"user,",
      :action=>"to download the application",
      :result=>"I can request a car.",
      :estimated_points=>5 },
    { :role=>"user,",
      :action=>"to see how much time it will take for the car to reach me",
      :result=>"I am ready to go when it arrives.",
      :estimated_points=>5 },
    { :role=>"user,",
      :action=>"to see who my driver will be",
      :result=>"I can view their information and feedback.",
      :estimated_points=>3 },
    { :role=>"admin,",
      :action=>"to send the user an email to verify their email address when it is added or updated in the system",
      :result=>"I can be sure they are a real person.",
      :estimated_points=>2 },
    { :role=>"user,",
      :action=>"to enter promotion codes I have received",
      :result=>"I can get a free ride.",
      :estimated_points=>3 },
    { :role=>"user,",
      :action=>"to see the route that will be taken between my pickup and my destination",
      :result=>"I can see what the cost is based on.",
      :estimated_points=>3 },
    { :role=>"user,",
      :action=>"to access my settings ",
      :result=>"I can change or update information.",
      :estimated_points=>3 },
    { :role=>"user,",
      :action=>"to see the full list of notifications that I have received within the app",
      :result=>"I do not miss anything that has been sent to me.",
      :estimated_points=>5 },
    { :role=>"user,",
      :action=>"to select whether to allow push notifications",
      :result=>"I can receive information quickly.",
      :estimated_points=>1 },
    { :role=>"system,",
      :action=>"to use an image of a credit card to acquire the needed credit card information for payment",
      :result=>"the payment can go through when a user requests a ride.",
      :estimated_points=>5 },
    { :role=>"user,",
      :action=>"to enter my password to verify access to my settings ",
      :result=>"I can update my information.",
      :estimated_points=>1 },
    { :role=>"user,",
      :action=>"to cancel out of editing my profile",
      :result=>"I do not make any changes I don't want or need to.",
      :estimated_points=>1 },
    { :role=>"user,",
      :action=>"to edit my name",
      :result=>"I can change it to whatever I need it to be.",
      :estimated_points=>1 },
    { :role=>"user,",
      :action=>"to retrieve my password",
      :result=>"I can verify my account information.",
      :estimated_points=>3 },
    { :role=>"user,",
      :action=>"to select a location for work",
      :result=>"I can select it quickly when requesting a ride.",
      :estimated_points=>2 },
    { :role=>"user,",
      :action=>"to get help",
      :result=>"I can resolve any issues I might have.",
      :estimated_points=>1 }
  ]

  project.owner = User.find_by(email:'admin@getarbor.io')
  story = UserStory.new(
    role: 'user',
    action: 'to be able to request the luxury tier',
    result: 'I can ride in comfort and style')
  project.user_stories << story
  story.acceptance_criterions << AcceptanceCriterion
    .new(description: 'Verify that luxury tier is available anywhere when I need it')

  stories_array.each do |story|
    new_story = UserStory.new(
      role: story[:role],
      action: story[:action],
      result: story[:result],
      estimated_points: story[:estimated_points])
    project.user_stories << new_story
  end

  project.canvas = Canvas.new(problems: "It's difficult to get a taxi in town")
  project.save
end
